// apps/playground-vue/src/App.vue
<script setup lang="ts">
import ApiEndpointButton from './components/ApiEndpointButton.vue'
import ResponseDisplay from './components/ResponseDisplay.vue'
</script>

<template>
  <div class="flex h-screen w-screen flex-col items-center justify-center gap-5 px-5 md:px-20">
    <ApiEndpointButton />
    <div class="relative w-full max-w-4xl">
      <ResponseDisplay />
    </div>
  </div>
</template>

// apps/service/src/app/page.tsx
import { TestComponent as TestComponentUnbundled } from "sample-next-react-package"
import { TestComponent } from "sample-react-package"

export default function Home() {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      <TestComponent />
      <TestComponentUnbundled />
    </main>
  )
}
