// apps/playground/src/FetchTest.tsx
import { useQueryClient, useSuspenseQuery } from "@tanstack/react-query"

export default function FetchTest({ targetUrl }: { targetUrl: string }) {
  const queryClient = useQueryClient()
  const { data } = useSuspenseQuery({
    queryKey: [targetUrl],
    queryFn: async () => {
      const response = await fetch(targetUrl)
      return await response.json()
    }
  })

  return (
    <div
      style={{
        width: "33%",
        padding: "1rem"
      }}
    >
      <span
        style={{
          display: "block"
        }}
      >
        URL:{" "}
      </span>
      <span
        style={{
          display: "block",
          fontFamily:
            "'Courier New', Courier, 'Lucida Console', 'Lucida Sans Typewriter', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Nimbus Mono L', Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
          wordBreak: "break-all"
        }}
      >
        {targetUrl}
      </span>
      <button
        style={{
          marginTop: "1rem"
        }}
        type='button'
        onClick={() =>
          queryClient.resetQueries({
            queryKey: [targetUrl]
          })
        }
      >
        REFETCH
      </button>
      <div
        style={{
          marginTop: "1rem"
        }}
      >
        Response:{" "}
      </div>
      <pre
        style={{
          overflow: "auto"
        }}
      >
        {JSON.stringify(data, null, 2)}
      </pre>
    </div>
  )
}

// apps/playground-vue/src/components/FetchTest.vue
<script setup lang="ts">
import { useQuery, useQueryClient } from '@tanstack/vue-query'

const props = defineProps<{
  targetUrl: string
}>()

const { data, suspense } = useQuery({
  queryKey: [props.targetUrl],
  queryFn: async () => {
    const response = await fetch(props.targetUrl)
    return await response.json()
  }
})

await suspense()

const queryClient = useQueryClient()

const handleClick = async () => {
  queryClient.resetQueries({
    queryKey: [props.targetUrl]
  })
}
</script>

<style module>
.wrapper {
  width: 33%;
  padding: 1rem;
}
.targetUrl {
  display: 'block';
  font-family: 'Courier New', Courier, 'Lucida Console', 'Lucida Sans Typewriter',
    'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Andale Mono', 'Nimbus Mono L', Monaco, Consolas,
    'Liberation Mono', 'Courier New', monospace;
  word-break: break-all;
}
.button {
  margin-top: 1rem;
}
.response {
  margin-top: 1rem;
}
.pre {
  overflow: auto;
}
</style>

<template>
  <div :class="$style.wrapper">
    <div>
      <div>URL:</div>
      <div :class="$style.targetUrl">{{ targetUrl }}</div>
    </div>
    <button :class="$style.button" type="button" @click="handleClick">REFETCH</button>
    <div :class="$style.response">Response:</div>
    <pre :class="$style.pre">{{ JSON.stringify(data, null, 2) }}</pre>
  </div>
</template>
