// apps/playground/src/ResponseDisplay.tsx
import { useQueryClient, useSuspenseQuery } from "@tanstack/react-query"
import clsx from "clsx"
import { Suspense } from "react"
import { FallbackProps } from "react-error-boundary"

import { JsonHighlighter } from "./JsonHighlighter"
import { query } from "./queryOptions"
import { ReloadButton } from "./ReloadButton"

export const ResponseDisplay = () => {
  const queryClient = useQueryClient()

  return (
    <div className='w-full max-w-4xl'>
      <h2 className='flex items-center rounded-t-lg bg-gray-700 px-2 py-1 font-mono font-bold'>
        Response
        <Suspense>
          <SuspendedResponseStatusDisplay className='ml-2' />
        </Suspense>
        <ReloadButton
          className='ml-auto'
          onClick={() =>
            queryClient.resetQueries({
              queryKey: query.custardStatus().queryKey
            })
          }
        >
          Reload
        </ReloadButton>
      </h2>
      <div className='overflow-hidden rounded-b-lg'>
        <Suspense fallback={<JsonHighlighter>loading...</JsonHighlighter>}>
          <SuspendedDisplay />
        </Suspense>
      </div>
    </div>
  )
}

export const ResponseErrorDisplay = ({
  error,
  resetErrorBoundary
}: FallbackProps) => {
  return (
    <div className='w-full max-w-4xl'>
      <h2 className='flex items-center rounded-t-lg bg-gray-700 px-2 py-1 font-mono font-bold'>
        Response
        <ResponseStatusDisplay className='ml-2' status={error.status} />
        <ReloadButton className='ml-auto' onClick={resetErrorBoundary}>
          Reset
        </ReloadButton>
      </h2>
      <div className='overflow-hidden rounded-b-lg'>
        <JsonHighlighter>
          {JSON.stringify(error.response, null, 2)}
        </JsonHighlighter>
      </div>
    </div>
  )
}

const SuspendedResponseStatusDisplay = ({
  className
}: {
  className?: string
}) => {
  const { data } = useSuspenseQuery(query.custardStatus())

  return <ResponseStatusDisplay className={className} status={data.status} />
}

const ResponseStatusDisplay = ({
  status,
  className
}: {
  status: number
  className?: string
}) => {
  const color = status < 400 ? "text-green-500" : "text-red-500"

  return <span className={clsx(color, className)}>{status}</span>
}

const SuspendedDisplay = () => {
  const {
    data: { response }
  } = useSuspenseQuery(query.custardStatus())

  return <JsonHighlighter>{JSON.stringify(response, null, 2)}</JsonHighlighter>
}

// apps/playground-vue/src/components/ResponseDisplay.vue
<template>
  <div class="w-full max-w-4xl">
    <h2 class="flex items-center rounded-t-lg bg-gray-700 px-2 py-1 font-mono font-bold">
      Response
      <span :class="['ml-2', statusColor]">{{ responseData.status }}</span>
      <ReloadButton class="ml-auto" @click="refetch"> Reload </ReloadButton>
    </h2>
    <div class="overflow-hidden rounded-b-lg">
      <JsonHighlighter :code="isFetching ? 'Loading...' : jsonData" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { computed } from 'vue'
import ReloadButton from './ReloadButton.vue'
import JsonHighlighter from './JsonHighlighter.vue'
import { fetchCustardStatus } from '@/queryOptions'

const { data, isFetching, refetch } = useQuery({
  queryKey: ['custardStatus'],
  queryFn: fetchCustardStatus
})

const responseData = computed(() => data.value || { status: 200, response: 'Loading...' })
const jsonData = computed(() => JSON.stringify(responseData.value.response, null, 2))
const statusColor = computed(() =>
  responseData.value.status < 400 ? 'text-green-500' : 'text-red-500'
)
</script>
