// apps/playground/src/App.tsx
import "./reset.css"

import { QueryClient, QueryClientProvider } from "@tanstack/react-query"

import FetchTest from "./FetchTest"
import { QuerySuspenseBoundary } from "./QuerySuspenseBoundary"

const queryClient = new QueryClient()

function App() {
  return (
    <>
      <h3>
        <a
          href='https://www.npmjs.com/package/@custardcream/msw-devtools'
          target='_blank'
          rel='noreferrer'
        >
          @custardcream/msw-devtools
        </a>{" "}
        Demo
      </h3>
      <p
        style={{
          lineHeight: "1.5",
          width: "100%"
        }}
      >
        Try adding mock request handler of APIs below and click{" "}
        <code>REFETCH</code> button to see the request gets mocked.
      </p>
      <QueryClientProvider client={queryClient}>
        <div
          style={{
            display: "flex",
            width: "100%",
            maxWidth: "1200px",
            margin: "0 auto"
          }}
        >
          <QuerySuspenseBoundary>
            <FetchTest targetUrl='https://api.sampleapis.com/switch/games' />
          </QuerySuspenseBoundary>
          <QuerySuspenseBoundary>
            <FetchTest targetUrl='https://api.sampleapis.com/recipes/recipes' />
          </QuerySuspenseBoundary>
          <QuerySuspenseBoundary>
            <FetchTest targetUrl='https://api.sampleapis.com/wines/reds' />
          </QuerySuspenseBoundary>
        </div>
      </QueryClientProvider>
    </>
  )
}

export default App

// apps/playground-vue/src/App.vue
<script setup lang="ts">
import FetchTest from './components/FetchTest.vue'
</script>

<style module>
.wrapper {
  display: flex;
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
}
.description {
  line-height: 1.5;
}
</style>

<template>
  <h3>
    <a
      href="https://www.npmjs.com/package/@custardcream/msw-devtools"
      target="_blank"
      rel="noreferrer"
    >
      @custardcream/msw-devtools
    </a>
    Vue.js Demo
  </h3>
  <p :class="$style.description">
    Try adding mock request handler of APIs below and click <code>REFETCH</code> button to see the
    request gets mocked.
  </p>
  <div :class="$style.wrapper">
    <Suspense>
      <template #default>
        <FetchTest targetUrl="https://api.sampleapis.com/switch/games" />
      </template>
      <template #fallback>
        <div>Loading...</div>
      </template>
    </Suspense>
    <Suspense>
      <template #default>
        <FetchTest targetUrl="https://api.sampleapis.com/recipes/recipes" />
      </template>
      <template #fallback>
        <div>Loading...</div>
      </template>
    </Suspense>
    <Suspense>
      <template #default>
        <FetchTest targetUrl="https://api.sampleapis.com/wines/reds" />
      </template>
      <template #fallback>
        <div>Loading...</div>
      </template>
    </Suspense>
  </div>
</template>
