// apps/playground-vue/src/components/ReloadButton.vue
<template>
  <button
    type="button"
    :class="[
      'cursor-pointer rounded-xl bg-gray-600 px-3 py-1 text-sm',
      'transition-all duration-300',
      'hover:[:not(:disabled)]:bg-gray-900',
      'disabled:cursor-progress disabled:opacity-50',
      className
    ]"
    :disabled="!!isFetchingCount"
    @click="handleClick"
  >
    <slot>Reload</slot>
  </button>
</template>

<script setup lang="ts">
import { useIsFetching } from '@tanstack/vue-query'
import { computed } from 'vue'

const props = defineProps<{
  className?: string
}>()

const emit = defineEmits<{
  (event: 'click'): void
}>()

const isFetchingCount = useIsFetching()
const className = computed(() => props.className || '')

const handleClick = () => {
  emit('click')
}
</script>

// apps/playground/src/ReloadButton.tsx
import { useIsFetching } from "@tanstack/react-query"
import clsx from "clsx"

export const ReloadButton = ({
  className,
  children,
  ...props
}: React.ButtonHTMLAttributes<HTMLButtonElement>) => {
  const isFetching = !!useIsFetching()

  return (
    <button
      type='button'
      className={clsx(
        "cursor-pointer rounded-xl bg-gray-600 px-3 py-1 text-sm",
        "transition-all duration-300",
        "hover:[:not(:disabled)]:bg-gray-900",
        "disabled:cursor-progress disabled:opacity-50",
        className
      )}
      disabled={isFetching}
      {...props}
    >
      {children}
    </button>
  )
}
